# Generated by Django 3.2.6 on 2021-12-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='CustomerID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='EmployeeID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='Freight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ShipAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ShipCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ShipCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ShipName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ShipPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ShipRegion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='Verified',
            field=models.TextField(blank=True, null=True),
        ),
    ]
