# Generated by Django 3.2.6 on 2022-01-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_system', '0003_auto_20220104_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassID', models.PositiveIntegerField()),
                ('ClassName', models.TextField(blank=True, null=True)),
                ('Color', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MachineID', models.PositiveIntegerField()),
                ('MachineName', models.TextField(blank=True, null=True)),
                ('Color', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
        migrations.RenameField(
            model_name='mechanical_hours',
            old_name='Subjuct',
            new_name='Subject',
        ),
        migrations.AlterField(
            model_name='mechanical_hours',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mechanical_hours',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
