# Generated by Django 3.2.6 on 2021-11-30 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='創建時間', verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改時間', verbose_name='修改時間')),
                ('is_deleted', models.BooleanField(default=False, help_text='刪除標記', verbose_name='刪除標記')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='製令')),
                ('status', models.CharField(blank=True, max_length=5, null=True, verbose_name='狀態')),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='開始時間', null=True, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='結束時間', null=True, verbose_name='結束時間')),
            ],
            options={
                'verbose_name': '製令',
                'verbose_name_plural': '製令',
            },
        ),
    ]
