# Generated by Django 3.2.6 on 2021-11-30 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_system', '0002_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='結束時間', null=True, verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='開始時間', null=True, verbose_name='開始時間'),
        ),
    ]
