# Generated by Django 3.2.6 on 2021-11-30 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report_system', '0003_auto_20211130_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='結束時間', null=True, verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='開始時間', null=True, verbose_name='開始時間'),
        ),
    ]
