# Generated by Django 3.2.6 on 2022-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagid', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
