# Generated by Django 3.2.6 on 2022-03-07 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='創建時間', verbose_name='創建時間')),
                ('is_deleted', models.BooleanField(default=False, help_text='刪除標記', verbose_name='刪除標記')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='批號')),
                ('storage_spaces', models.CharField(blank=True, max_length=5, null=True, verbose_name='儲位')),
                ('update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='更新時間', null=True, verbose_name='更新時間')),
            ],
            options={
                'db_table': 'warehouse_management',
            },
        ),
    ]
