# Generated by Django 3.2.6 on 2022-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_list',
            name='user',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='確認者'),
        ),
    ]
